version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: bilimp_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - bilimp_network

  ollama:
    image: ollama/ollama:latest
    container_name: bilimp_ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_models:/root/.ollama
    restart: unless-stopped
    networks:
      - bilimp_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  bilimp_network:
    driver: bridge
